ASG EC2 Auto EIP
hazelops/terraform-aws-ecs-app pull request #8
Opened 2022-01-28 16:08 UTC by igorkotof

2022-01-28 20:19 UTC, AutomationD requested changes
Looks good, thank you. There are some suggestions though.

2022-01-28 20:19 UTC, AutomationD commented on data.tf
> +    auto_assign_eip   = var.ec2_asg_auto_assign_eip
Can we use https://www.terraform.io/language/functions/tostring here and switch the whole var to bool?

2022-01-28 20:19 UTC, AutomationD commented on autoscaling.tf
> +}
I'd prefer a new line here please

2022-01-28 20:19 UTC, AutomationD commented on ecs_ec2_user_data.sh.tpl
> +apt-get update
As far as I know AWS ECS optimized AMI is is RHEL based, any reason to use ubuntu for that?

2022-01-28 20:19 UTC, AutomationD commented on ecs_ec2_user_data.sh.tpl
> +	instance_id=$( (curl http://169.254.169.254/latest/meta-data/instance-id) )
Any reason why there are double braces?

2022-01-28 20:19 UTC, AutomationD commented on autoscaling.tf
> +  tags = {
Should we add some sequential id here?

2022-01-28 20:19 UTC, AutomationD commented on variables.tf
> +  type        = string
If we use `tostring()` in the template, we could switch to bool here, I think

2022-01-30 11:10 UTC, igorkotof commented on autoscaling.tf
> +  tags = {
it's not needed @AutomationD

2022-01-30 12:09 UTC, merged